// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (body, tag, created_at, updated_at, last_reviewed_at) 
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
)
RETURNING id, body, tag, created_at, last_reviewed_at, review_interval_days, review_count, ease_factor, updated_at
`

type CreateEntryParams struct {
	Body           string
	Tag            sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastReviewedAt time.Time
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.Body,
		arg.Tag,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastReviewedAt,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.Tag,
		&i.CreatedAt,
		&i.LastReviewedAt,
		&i.ReviewIntervalDays,
		&i.ReviewCount,
		&i.EaseFactor,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries
WHERE id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const editEntry = `-- name: EditEntry :exec
UPDATE entries
SET body = ?, tag = ?, updated_at = ?
WHERE id = ?
`

type EditEntryParams struct {
	Body      string
	Tag       sql.NullString
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) EditEntry(ctx context.Context, arg EditEntryParams) error {
	_, err := q.db.ExecContext(ctx, editEntry,
		arg.Body,
		arg.Tag,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const getDueEntries = `-- name: GetDueEntries :many
SELECT id, body, tag, created_at, last_reviewed_at, review_interval_days, review_count, ease_factor, updated_at
FROM entries
WHERE last_reviewed_at IS NULL
   OR datetime(last_reviewed_at, '+' || review_interval_days || ' days') <= datetime('now')
ORDER BY last_reviewed_at ASC NULLS FIRST
`

func (q *Queries) GetDueEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getDueEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.Tag,
			&i.CreatedAt,
			&i.LastReviewedAt,
			&i.ReviewIntervalDays,
			&i.ReviewCount,
			&i.EaseFactor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntry = `-- name: GetEntry :one
SELECT id, body, tag, created_at, last_reviewed_at, review_interval_days, review_count, ease_factor, updated_at FROM entries
WHERE id = ?
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.Tag,
		&i.CreatedAt,
		&i.LastReviewedAt,
		&i.ReviewIntervalDays,
		&i.ReviewCount,
		&i.EaseFactor,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllEntry = `-- name: ListAllEntry :many
SELECT id, body, tag, created_at, last_reviewed_at, review_interval_days, review_count, ease_factor, updated_at FROM entries
`

func (q *Queries) ListAllEntry(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listAllEntry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.Tag,
			&i.CreatedAt,
			&i.LastReviewedAt,
			&i.ReviewIntervalDays,
			&i.ReviewCount,
			&i.EaseFactor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :exec
UPDATE entries
SET last_reviewed_at     = ?,
    review_interval_days = ?,
    ease_factor          = ?,
    review_count         = review_count + 1
WHERE id = ?
`

type UpdateReviewParams struct {
	LastReviewedAt     time.Time
	ReviewIntervalDays int64
	EaseFactor         float64
	ID                 int64
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) error {
	_, err := q.db.ExecContext(ctx, updateReview,
		arg.LastReviewedAt,
		arg.ReviewIntervalDays,
		arg.EaseFactor,
		arg.ID,
	)
	return err
}
