// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const countAllEntries = `-- name: CountAllEntries :one
SELECT COUNT(*) FROM entries
`

func (q *Queries) CountAllEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDueEntries = `-- name: CountDueEntries :one
SELECT COUNT(*) FROM entries
WHERE (
    review_count = 0
    OR datetime(last_reviewed_at, '+' || review_interval_days || ' days') <= datetime('now')
)
`

func (q *Queries) CountDueEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDueEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEntriesByTag = `-- name: CountEntriesByTag :many
SELECT tag, COUNT(*) AS count
FROM entries
GROUP BY tag
ORDER BY count DESC
`

type CountEntriesByTagRow struct {
	Tag   string
	Count int64
}

func (q *Queries) CountEntriesByTag(ctx context.Context) ([]CountEntriesByTagRow, error) {
	rows, err := q.db.QueryContext(ctx, countEntriesByTag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountEntriesByTagRow
	for rows.Next() {
		var i CountEntriesByTagRow
		if err := rows.Scan(&i.Tag, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countReviewedEntries = `-- name: CountReviewedEntries :one
SELECT COUNT(*) FROM entries
WHERE review_count > 0
`

func (q *Queries) CountReviewedEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReviewedEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreviewedEntries = `-- name: CountUnreviewedEntries :one
SELECT COUNT(*) FROM entries
WHERE review_count = 0
`

func (q *Queries) CountUnreviewedEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreviewedEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (body, tag, created_at, updated_at, last_reviewed_at) 
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
)
RETURNING id, body, tag, created_at, last_reviewed_at, review_interval_days, review_count, ease_factor, updated_at
`

type CreateEntryParams struct {
	Body           string
	Tag            string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastReviewedAt time.Time
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.Body,
		arg.Tag,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastReviewedAt,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.Tag,
		&i.CreatedAt,
		&i.LastReviewedAt,
		&i.ReviewIntervalDays,
		&i.ReviewCount,
		&i.EaseFactor,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllEntries = `-- name: DeleteAllEntries :execrows
DELETE FROM entries
`

func (q *Queries) DeleteAllEntries(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAllEntries)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEntriesByTag = `-- name: DeleteEntriesByTag :execrows
DELETE FROM entries
WHERE LOWER(TRIM(tag)) = LOWER(TRIM(?))
`

func (q *Queries) DeleteEntriesByTag(ctx context.Context, trim string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEntriesByTag, trim)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEntry = `-- name: DeleteEntry :execresult
DELETE FROM entries
WHERE id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEntry, id)
}

const editEntry = `-- name: EditEntry :exec
UPDATE entries
SET body = ?, tag = ?, updated_at = ?
WHERE id = ?
`

type EditEntryParams struct {
	Body      string
	Tag       string
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) EditEntry(ctx context.Context, arg EditEntryParams) error {
	_, err := q.db.ExecContext(ctx, editEntry,
		arg.Body,
		arg.Tag,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const getDueEntries = `-- name: GetDueEntries :many
SELECT id, body, tag, created_at, last_reviewed_at, review_interval_days, review_count, ease_factor, updated_at
FROM entries
WHERE (
    review_count = 0
    OR datetime(last_reviewed_at, '+' || review_interval_days || ' days') <= datetime('now')
)
ORDER BY review_count ASC, last_reviewed_at ASC
`

func (q *Queries) GetDueEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getDueEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.Tag,
			&i.CreatedAt,
			&i.LastReviewedAt,
			&i.ReviewIntervalDays,
			&i.ReviewCount,
			&i.EaseFactor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntriesByTag = `-- name: GetEntriesByTag :many
SELECT id, body, tag, created_at, last_reviewed_at, review_interval_days, review_count, ease_factor, updated_at FROM entries
WHERE LOWER(TRIM(tag)) = LOWER(TRIM(?))
ORDER BY id ASC
`

func (q *Queries) GetEntriesByTag(ctx context.Context, trim string) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getEntriesByTag, trim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.Tag,
			&i.CreatedAt,
			&i.LastReviewedAt,
			&i.ReviewIntervalDays,
			&i.ReviewCount,
			&i.EaseFactor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryByID = `-- name: GetEntryByID :one
SELECT id, body, tag, created_at, last_reviewed_at, review_interval_days, review_count, ease_factor, updated_at FROM entries
WHERE id = ?
`

func (q *Queries) GetEntryByID(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryByID, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.Tag,
		&i.CreatedAt,
		&i.LastReviewedAt,
		&i.ReviewIntervalDays,
		&i.ReviewCount,
		&i.EaseFactor,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllEntry = `-- name: ListAllEntry :many
SELECT id, body, tag, created_at, last_reviewed_at, review_interval_days, review_count, ease_factor, updated_at FROM entries
ORDER BY id ASC
`

func (q *Queries) ListAllEntry(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listAllEntry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.Tag,
			&i.CreatedAt,
			&i.LastReviewedAt,
			&i.ReviewIntervalDays,
			&i.ReviewCount,
			&i.EaseFactor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryPaginated = `-- name: ListEntryPaginated :many
SELECT id, body, tag, created_at, last_reviewed_at, review_interval_days, review_count, ease_factor, updated_at FROM entries
ORDER BY id ASC
LIMIT ? OFFSET ?
`

type ListEntryPaginatedParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListEntryPaginated(ctx context.Context, arg ListEntryPaginatedParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntryPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.Tag,
			&i.CreatedAt,
			&i.LastReviewedAt,
			&i.ReviewIntervalDays,
			&i.ReviewCount,
			&i.EaseFactor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAllReviews = `-- name: ResetAllReviews :execrows
UPDATE entries
SET last_reviewed_at     = ?,
    review_interval_days = 1,
    ease_factor          = 2.5,
    review_count         = 0
`

func (q *Queries) ResetAllReviews(ctx context.Context, lastReviewedAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetAllReviews, lastReviewedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateReview = `-- name: UpdateReview :exec
UPDATE entries
SET last_reviewed_at     = ?,
    review_interval_days = ?,
    ease_factor          = ?,
    review_count         = ?
WHERE id = ?
`

type UpdateReviewParams struct {
	LastReviewedAt     time.Time
	ReviewIntervalDays int64
	EaseFactor         float64
	ReviewCount        int64
	ID                 int64
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) error {
	_, err := q.db.ExecContext(ctx, updateReview,
		arg.LastReviewedAt,
		arg.ReviewIntervalDays,
		arg.EaseFactor,
		arg.ReviewCount,
		arg.ID,
	)
	return err
}
