// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (body, tag, created_at) 
VALUES (
    ?,
    ?,
    ?
)
RETURNING id, body, tag, created_at, last_reviewed_at, review_interval_days, review_count
`

type CreateEntryParams struct {
	Body      string
	Tag       sql.NullString
	CreatedAt time.Time
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.Body, arg.Tag, arg.CreatedAt)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.Tag,
		&i.CreatedAt,
		&i.LastReviewedAt,
		&i.ReviewIntervalDays,
		&i.ReviewCount,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries
WHERE id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const listAllEntry = `-- name: ListAllEntry :many
SELECT id, body, tag, created_at, last_reviewed_at, review_interval_days, review_count FROM entries
`

func (q *Queries) ListAllEntry(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listAllEntry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.Tag,
			&i.CreatedAt,
			&i.LastReviewedAt,
			&i.ReviewIntervalDays,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
