// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lessons.sql

package database

import (
	"context"
	"database/sql"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (body, tag) 
VALUES (
    ?,
    ?
)
RETURNING id, body, tag, created_at, last_reviewed_at, review_interval_days, review_count
`

type CreateEntryParams struct {
	Body string
	Tag  sql.NullString
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.Body, arg.Tag)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.Tag,
		&i.CreatedAt,
		&i.LastReviewedAt,
		&i.ReviewIntervalDays,
		&i.ReviewCount,
	)
	return i, err
}
