// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lessons.sql

package database

import (
	"context"
	"database/sql"
)

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (body, tag) 
VALUES (
    ?,
    ?
)
RETURNING id, body, tag, created_at, last_reviewed_at, review_interval_days, review_count
`

type CreateLessonParams struct {
	Body string
	Tag  sql.NullString
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, createLesson, arg.Body, arg.Tag)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.Tag,
		&i.CreatedAt,
		&i.LastReviewedAt,
		&i.ReviewIntervalDays,
		&i.ReviewCount,
	)
	return i, err
}
