// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type Entry struct {
	ID                 int64
	Body               string
	Tag                sql.NullString
	CreatedAt          time.Time
	LastReviewedAt     time.Time
	ReviewIntervalDays int64
	ReviewCount        int64
	EaseFactor         float64
	UpdatedAt          time.Time
}
